---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - tekton.hrk091.dev
  resources:
  - retryablepipelineruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tekton.hrk091.dev
  resources:
  - retryablepipelineruns/finalizers
  verbs:
  - update
- apiGroups:
  - tekton.hrk091.dev
  resources:
  - retryablepipelineruns/status
  verbs:
  - get
  - patch
  - update
