/*
 Copyright 2022 Hiroki Okui.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

package v1alpha1

import (
	pipelinev1beta1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1"
	"github.com/tektoncd/pipeline/pkg/names"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"knative.dev/pkg/apis"
	duckv1beta1 "knative.dev/pkg/apis/duck/v1beta1"
)

// RetryablePipelineRunStatus defines the observed state of RetryablePipelineRun.
type RetryablePipelineRunStatus struct {
	duckv1beta1.Status `json:",inline"`

	// StartTime is the time the RetryablePipelineRun is actually started.
	// +optional
	StartTime *metav1.Time `json:"startTime,omitempty"`

	// CompletionTime is the time the RetryablePipelineRun completed.
	// +optional
	CompletionTime *metav1.Time `json:"completionTime,omitempty"`

	// PinnedPipelineRun contains the exact spec used to instantiate the first run.
	PinnedPipelineRun *pipelinev1beta1.PipelineRun `json:"pinnedPipelineRun,omitempty"`

	// PipelineRuns is the list of child PipelineRun status copies with using its name as the merge key.
	// +optional
	PipelineRuns []*PartialPipelineRunStatus `json:"pipelineRuns,omitempty"`

	// TaskResults is the map of TaskResult with the PipelineTask name as the key.
	// +optional
	TaskResults map[string]*CompletedTaskResults `json:"taskResults,omitempty"`

	// PipelineResults is the list of results written out by the pipeline task's containers.
	// +optional
	// +listType=atomic
	PipelineResults []pipelinev1beta1.PipelineRunResult `json:"pipelineResults,omitempty"`

	// RetryKey is the copy of retry-key annotation to compare with its previous value.
	RetryKey string
}

// InitializeStatus initializes the RetryablePipelineRun status.
func (rpr *RetryablePipelineRun) InitializeStatus() {
	if rpr.Status == nil {
		rpr.Status = &RetryablePipelineRunStatus{
			PipelineRuns:    []*PartialPipelineRunStatus{},
			PipelineResults: []pipelinev1beta1.PipelineRunResult{},
		}
		rpr.InitializeConditions()
	}
}

// AggregateChildrenResults aggregates belonging PipelineRun/TaskRun statuses
// and populates RetryablePipelineRunStatus with their latest statuses.
func (rpr *RetryablePipelineRun) AggregateChildrenResults() {
	m := map[string]*CompletedTaskResults{}
	for _, pr := range rpr.Status.PipelineRuns {
		for _, tr := range pr.TaskRuns {
			if !tr.Status.GetCondition(apis.ConditionSucceeded).IsTrue() {
				continue
			}
			if _, ok := m[tr.PipelineTaskName]; ok {
				continue
			}
			m[tr.PipelineTaskName] = &CompletedTaskResults{
				CompletedAt: pr.Name,
				Results:     tr.Status.TaskRunResults,
			}
		}
	}
	rpr.Status.TaskResults = m

	lastPr := rpr.Status.PipelineRuns[len(rpr.Status.PipelineRuns)-1]
	lastCond := lastPr.GetCondition()
	rpr.Status.SetCondition(lastCond.DeepCopy())
	if lastCond.IsTrue() {
		rpr.Status.PipelineResults = lastPr.PipelineResults
	}
}

// CompletedTaskResults contains the TaskRunResults generated by belonging PipelineRuns.
type CompletedTaskResults struct {
	// CompletedAt shows the name of PipelineRun where the task result is written.
	CompletedAt string `json:"completedAt,omitempty"`

	// Results are the list of results written out by the task's containers
	// +optional
	// +listType=atomic
	Results []pipelinev1beta1.TaskRunResult `json:"results,omitempty"`
}

// PartialPipelineRunStatus contains the fields of belonging PipelineRuns' status.
type PartialPipelineRunStatus struct {
	duckv1beta1.Status `json:",inline"`

	// Name is the name of PipelineRun as well as the primary key of PartialPipelineRunStatus collection.
	Name string `json:"name"`

	// StartTime is the time the PipelineRun is actually started.
	// +optional
	StartTime *metav1.Time `json:"startTime,omitempty"`

	// CompletionTime is the time the PipelineRun completed.
	// +optional
	CompletionTime *metav1.Time `json:"completionTime,omitempty"`

	// PipelineResults are the list of results written out by the pipeline task's containers
	// +optional
	// +listType=atomic
	PipelineResults []pipelinev1beta1.PipelineRunResult `json:"pipelineResults,omitempty"`

	// SkippedTasks is the list of tasks that were skipped due to when expressions evaluating to false.
	// +optional
	// +listType=atomic
	SkippedTasks []pipelinev1beta1.SkippedTask `json:"skippedTasks,omitempty"`

	// TaskRuns is the map of PipelineRunTaskRunStatus with the taskRun name as the key.
	// +optional
	TaskRuns map[string]*pipelinev1beta1.PipelineRunTaskRunStatus `json:"taskRuns,omitempty"`
}

func (rpr *RetryablePipelineRun) IsRetryKeyChanged() bool {
	return RetryKey(&rpr.ObjectMeta) != rpr.Status.RetryKey
}

func (rpr *RetryablePipelineRun) CopyRetryKey() {
	rpr.Status.RetryKey = RetryKey(&rpr.ObjectMeta)
}

func (s *PartialPipelineRunStatus) CopyFrom(pr *pipelinev1beta1.PipelineRunStatus) {
	s.StartTime = pr.StartTime
	s.CompletionTime = pr.CompletionTime
	s.Conditions = pr.Conditions
	s.SkippedTasks = pr.SkippedTasks
	s.TaskRuns = pr.TaskRuns
	s.PipelineResults = pr.PipelineResults
}

func (rpr *RetryablePipelineRun) PipelineRunStatus(name string) *PartialPipelineRunStatus {
	for _, pr := range rpr.Status.PipelineRuns {
		if pr.Name == name {
			return pr
		}
	}
	return nil
}

// ReserveNextPipelineRunName reserves a name of PipelineRun to be created at the next reconcile loop.
func (rpr *RetryablePipelineRun) ReserveNextPipelineRunName() bool {
	for _, pr := range rpr.Status.PipelineRuns {
		if pr.StartTime == nil {
			return false
		}
	}
	rpr.Status.PipelineRuns = append(rpr.Status.PipelineRuns, &PartialPipelineRunStatus{
		Name: rpr.genPipelineRunName(),
	})
	return true
}

// NextPipelineRunName returns a name of PipelineRun that should be used for the next PipelineRun.
func (rpr *RetryablePipelineRun) NextPipelineRunName() string {
	for _, pr := range rpr.Status.PipelineRuns {
		if pr.StartTime == nil {
			return pr.Name
		}
	}
	return ""
}

// StartedPipelineRunCount returns the number of child PipelineRuns already started.
func (rpr *RetryablePipelineRun) StartedPipelineRunCount() int {
	c := 0
	for _, pr := range rpr.Status.PipelineRuns {
		if pr.StartTime != nil {
			c++
		}
	}
	return c
}

func (rpr *RetryablePipelineRun) genPipelineRunName() string {
	return names.SimpleNameGenerator.RestrictLengthWithRandomSuffix(rpr.Name)
}
