//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Hiroki Okui.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompletedTaskResults) DeepCopyInto(out *CompletedTaskResults) {
	*out = *in
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]v1beta1.TaskRunResult, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompletedTaskResults.
func (in *CompletedTaskResults) DeepCopy() *CompletedTaskResults {
	if in == nil {
		return nil
	}
	out := new(CompletedTaskResults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartialPipelineRunStatus) DeepCopyInto(out *PartialPipelineRunStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.PipelineResults != nil {
		in, out := &in.PipelineResults, &out.PipelineResults
		*out = make([]v1beta1.PipelineRunResult, len(*in))
		copy(*out, *in)
	}
	if in.SkippedTasks != nil {
		in, out := &in.SkippedTasks, &out.SkippedTasks
		*out = make([]v1beta1.SkippedTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TaskRuns != nil {
		in, out := &in.TaskRuns, &out.TaskRuns
		*out = make(map[string]*v1beta1.PipelineRunTaskRunStatus, len(*in))
		for key, val := range *in {
			var outVal *v1beta1.PipelineRunTaskRunStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(v1beta1.PipelineRunTaskRunStatus)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartialPipelineRunStatus.
func (in *PartialPipelineRunStatus) DeepCopy() *PartialPipelineRunStatus {
	if in == nil {
		return nil
	}
	out := new(PartialPipelineRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryablePipelineRun) DeepCopyInto(out *RetryablePipelineRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(RetryablePipelineRunSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(RetryablePipelineRunStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryablePipelineRun.
func (in *RetryablePipelineRun) DeepCopy() *RetryablePipelineRun {
	if in == nil {
		return nil
	}
	out := new(RetryablePipelineRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RetryablePipelineRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryablePipelineRunList) DeepCopyInto(out *RetryablePipelineRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RetryablePipelineRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryablePipelineRunList.
func (in *RetryablePipelineRunList) DeepCopy() *RetryablePipelineRunList {
	if in == nil {
		return nil
	}
	out := new(RetryablePipelineRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RetryablePipelineRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryablePipelineRunSpec) DeepCopyInto(out *RetryablePipelineRunSpec) {
	*out = *in
	if in.PipelineRunSpec != nil {
		in, out := &in.PipelineRunSpec, &out.PipelineRunSpec
		*out = new(v1beta1.PipelineRunSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryablePipelineRunSpec.
func (in *RetryablePipelineRunSpec) DeepCopy() *RetryablePipelineRunSpec {
	if in == nil {
		return nil
	}
	out := new(RetryablePipelineRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryablePipelineRunStatus) DeepCopyInto(out *RetryablePipelineRunStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.PinnedPipelineRun != nil {
		in, out := &in.PinnedPipelineRun, &out.PinnedPipelineRun
		*out = new(v1beta1.PipelineRun)
		(*in).DeepCopyInto(*out)
	}
	if in.PipelineRuns != nil {
		in, out := &in.PipelineRuns, &out.PipelineRuns
		*out = make([]*PartialPipelineRunStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(PartialPipelineRunStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.TaskResults != nil {
		in, out := &in.TaskResults, &out.TaskResults
		*out = make(map[string]*CompletedTaskResults, len(*in))
		for key, val := range *in {
			var outVal *CompletedTaskResults
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(CompletedTaskResults)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.PipelineResults != nil {
		in, out := &in.PipelineResults, &out.PipelineResults
		*out = make([]v1beta1.PipelineRunResult, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryablePipelineRunStatus.
func (in *RetryablePipelineRunStatus) DeepCopy() *RetryablePipelineRunStatus {
	if in == nil {
		return nil
	}
	out := new(RetryablePipelineRunStatus)
	in.DeepCopyInto(out)
	return out
}
