name: Test-Operator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "UnitTest"

    strategy:
      matrix:
        go-version: [1.17]
        os: [ubuntu-latest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Use cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Downloads modules
        run: go mod download

      - name: Test
        run: make test
